// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBotorC3X7IUHezieui3GTcNLLzh3FUvHg',
    appId: '1:969777262856:web:b898c17d719016d6303cbd',
    messagingSenderId: '969777262856',
    projectId: 'doc-link-e5fb8',
    authDomain: 'doc-link-e5fb8.firebaseapp.com',
    storageBucket: 'doc-link-e5fb8.firebasestorage.app',
    measurementId: 'G-64921JE8ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp7xJ2iSyv7LKoLok8dQRc-2KcLKSST_M',
    appId: '1:969777262856:android:82a5e3bb1ea89de4303cbd',
    messagingSenderId: '969777262856',
    projectId: 'doc-link-e5fb8',
    storageBucket: 'doc-link-e5fb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO6qXddN0Lh_k-yJA-FXNU1yM46AngU3Y',
    appId: '1:969777262856:ios:285928bc6a3c59e3303cbd',
    messagingSenderId: '969777262856',
    projectId: 'doc-link-e5fb8',
    storageBucket: 'doc-link-e5fb8.firebasestorage.app',
    iosBundleId: 'com.example.eChanneling',
  );
}
